/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphstream;

public class App {

    public static void main(String[] args) {
        GraphGenerator graphGenerator = new GraphGenerator("Tree-Diagram",
                new int[] { 2, 4, 10, 13, 0 });
        graphGenerator.generate();
        // graphGenerator.display();
        // graphGenerator.find_solutions();

    }
}
